export const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PRISMA_ERROR: 'PRISMA_ERROR',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVALID_UUID: 'INVALID_UUID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  PHONE_ALREADY_IN_USE: 'PHONE_ALREADY_IN_USE',
  OTP_INVALID: 'OTP_INVALID'
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
