export const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PRISMA_ERROR: 'PRISMA_ERROR',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVALID_UUID: 'INVALID_UUID',
  USER_NOT_FOUND: 'USER_NOT_FOUND'
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
